keep variant setting removed by previous commit
to avoid error like:
===
$~/createhdds/createhdds.py  support
...
Traceback (most recent call last):
  File "/root/createhdds/createhdds.py", line 821, in <module>
    main()
  File "/root/createhdds/createhdds.py", line 811, in main
    args.func(args, hdds)
  File "/root/createhdds/createhdds.py", line 701, in cli_image
    img.create(args.textinst)
  File "/root/createhdds/createhdds.py", line 291, in create
    loctmp.format(fedoradir, str(self.release), variant, arch), "--name", "createhdds",
NameError: name 'variant' is not defined
===

Signed-off-by: Michel Normand <normand@linux.vnet.ibm.com>